DATA SEGMENT
	DAT DB 10 DUP(?)
DATA ENDS

CODE SEGMENT
ASSUME CS:CODE,DS:DATA
	START: MOV AX,DATA
		   MOV DS,AX
		   MOV CX,10
		   MOV BX,0
	LOOP1: MOV DAT[BX],BL
		   INC BX
	LOOP LOOP1
	ELOOP: JMP ELOOP
CODE ENDS
	END START