DATA SEGMENT
	BUF DB 9,8,7,6,5
	    DB 4,3,2,1,0
DATA ENDS

CODE SEGMENT
ASSUME CS:CODE,DS:DATA
	START: MOV AX,DATA
		   MOV DS,AX
		   MOV BX,0
		   MOV CX,10
		   DEC CX
	LOOP1: MOV DX,CX
	LOOP2: MOV AL,BUF[BX]
		   CMP AL,BUF[BX+1]
		   JBE GO
		   XCHG AL,BUF[BX+1]
		   MOV BUF[BX],AL
	GO:	   INC BX
		   LOOP LOOP2
		   MOV CX,DX
		   MOV BX,0
		   LOOP LOOP1
	ELOOP: JMP ELOOP
CODE ENDS 
	END START